### PR TITLE
Handle duplicate client creation error on application level

### LINKED ISSUE #54: Internal Server Error on duplicate client registration
When I try to register a client (with the following code) twice, I get an HTTP 500 ISE.

```
if ! x=$(curl -i -H "Accept: application/json" \
    -H "Content-type: application/json" \
    -H "Authorization: Bearer $tok" -X POST --data-binary @- \
    http://localhost:8080/osiam-auth-server/Client <<EOD
{
  "accessTokenValiditySeconds": "5000",
  "client_secret": "$osiamsecret",
  "grants": [
    "authorization_code",
    "client_credentials",
    "refresh_token",
    "password"
  ],
  "id": "online-registration",
  "implicit": "false",
  "redirectUri": "$verawebserver",
  "refreshTokenValiditySeconds": "5000",
  "scope": [
    "POST",
    "PUT",
    "GET",
    "DELETE",
    "PATCH"
  ],
  "validityInSeconds": "5000"
}
EOD
    ); then
        print -u2 E: cannot register client
        exit 1
fi
```

I get something back that begins with…

```
<html><head><title>Apache Tomcat/7.0.28 - Error report</title><style>
```

… and is basically illegible. The catalina.out logfile contains more information:

```
ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] - <ERROR: duplicate key value violates unique constraint "uk_c34iilt4h1ln91s9ro8m96hru"
  Detail: Key (id)=(online-registration) already exists.>
```

I’d have expected an application-level error signalling.

### PR DESCRIPTION
**Pull request by dacrome**
Respond with Conflict 409 when a client with a requested client id already exists
Fixes #54

### CODE REVIEW

**Comment by wallner** [comment]
Please fix the commit message and the PR description: it's either "respon_d_ with Conflict 409" or "emit Conflict 409 response" or something along those lines.

**Comment by tkrille** [comment]
@wallner I've assigned you, because it appears to me, that you already reviewing this one.

**Comment by tkrille** [comment]
Integration tests can be found here: https://github.com/osiam/connector4java-integration-tests/pull/267

File: src/main/java/org/osiam/auth/oauth_client/ClientDao.java [hunk 1]
```diff
@@ -75,12 +74,19 @@ private ClientEntity mergeClient(final ClientEntity client, final String id) {
...
-        final List<?> result = query.getResultList();
+        final List<ClientEntity> result = getClientResultList(id);
         if (result.isEmpty()) {
             throw new ResourceNotFoundException("Resource " + id + " not found.");
         }
-        return (ClientEntity) result.get(0);
+        return result.get(0);
+    }
+
+    public boolean isClientIdAlreadyTaken(String id) {
```
Comment (wallner) [inline src/main/java/org/osiam/auth/oauth_client/ClientDao.java]: I'm not very happy with this name: I would suggest `clientIdAllreadyExists`

**Comment by wallner** [comment]
Good thing you got rid of `ClientDaoSpec.groovy`

**Comment by dacrome** [comment]
Yes, but every test in [this package](https://github.com/osiam/auth-server/tree/master/src/test/groovy/org/osiam/auth/oauth_client) should be deleted.

File: src/main/java/org/osiam/auth/oauth_client/ClientDao.java (hunk 1 above)
Comment (dacrome) [inline src/main/java/org/osiam/auth/oauth_client/ClientDao.java]: Ok

**Comment by dacrome** [comment]
Updated

File: src/main/java/org/osiam/auth/exception/OsiamExceptionHandler.java [hunk 2]
```diff
@@ -60,6 +60,14 @@ protected JsonErrorResult handleResourceNotFound(HttpServletRequest request,
         return new JsonErrorResult(HttpStatus.NOT_FOUND.name(), e.getMessage());
     }
 
+    @ExceptionHandler(ClientAlreadyExistsException.class)
+    @ResponseStatus(HttpStatus.CONFLICT)
+    @ResponseBody
+    protected JsonErrorResult handleClientAlreadyExists(ClientAlreadyExistsException e) {
+        LOGGER.warn("A ClientAlreadyExistsException occurred", e);
```
Comment (wallner) [inline src/main/java/org/osiam/auth/exception/OsiamExceptionHandler.java]: Well, that the Exception occurred is easily visible from the delivered exception. I'm not even sure if I like the stack trace here, but I definitely would prefer a better log message, What do you think of "Tried to add client with id %id twice"?

Comment (dacrome) [inline src/main/java/org/osiam/auth/exception/OsiamExceptionHandler.java]: Yes, only the already [in the controller created exception message](https://github.com/dacrome/auth-server/blob/handle-duplicate-client-creation/src/main/java/org/osiam/auth/oauth_client/ClientManagementController.java#L75) should be logged. But I think it should be logged on info level instead of warn, right?

Comment (dacrome) [inline src/main/java/org/osiam/auth/exception/OsiamExceptionHandler.java]: No, I thought about it again and it should be logged on warn level

**Comment by wallner** [comment]
Thank you looks good.
